!!omap
- OUTPUT_DIR: exp_Gender_analysis_soft
- SAVE_CONFIG_NAME: config_Gender_analysis_soft.yaml
- CKPTS_DIR: /cvhci/temp/wpingcheng/ckpts_new/
- TYPE: AV+ConvBiLSTM+PHQ-Subscores+Attention
- MANUAL_SEED: 1
- LOG_TITLE: Depression Detection with audio and visual data, ConvBiLSTM, PHQ-Subscores,
    Fusion-Attention Layer, KLDivLoss , ASAM
- DATA: !!omap
  - TRAIN_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database_V2/train/clipped_data/
  - VALIDATION_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database_V2/train/original_data/
  - TEST_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database_V2/test/clipped_data/
  - USE_MEL_SPECTROGRAM: true
  - VISUAL_WITH_GAZE: true
  - PADDING:
  - RESCALE_SIZE:
  - CROP_SIZE:
  - BATCH_SIZE: 280
  - NUM_WORKERS: 0
- MODEL: !!omap
  - PHQ_THRESHOLD: 10
  - EPOCHS: 1
  - WEIGHTS: !!omap
    - TYPE: others
    - DATE:
    - PATH: model_weights
    - NAME: AV+ConvBiLSTM+PHQ-Subscores+Attention+Soft_2022-03-17_171149_acc-81.4286.pt
    - CUSTOM_ABSOLUTE_PATH:
    - INCLUDED:
      - audio_net
      - visual_net
      - fusion_net
      - evaluator
  - VISUAL_NET: !!omap
    - INPUT_DIM: 3
    - CONV_HIDDEN: 256
    - LSTM_HIDDEN: 256
    - OUTPUT_DIM: 256
    - NUM_LAYERS: 4
    - ACTIVATION: relu
    - NORM: bn
    - DROPOUT: 0.6
  - AUDIO_NET: !!omap
    - INPUT_DIM: 80
    - CONV_HIDDEN: 256
    - LSTM_HIDDEN: 256
    - OUTPUT_DIM: 256
    - NUM_LAYERS: 4
    - ACTIVATION: relu
    - NORM: bn
    - DROPOUT: 0.6
  - FUSION_NET: !!omap
    - INPUT_DIM: 1
    - HIDDEN_DIM: 4
    - BASE_WIDTH: 256
    - FUSE_TYPE: iAFF
  - EVALUATOR: !!omap
    - PREDICT_TYPE: phq-subscores
    - INPUT_FEATURE_DIM: 512
    - CLASSES_RESOLUTION: 32
    - N_CLASSES: 4
    - N_SUBSCORES: 8
    - STD: 5
  - CRITERION: !!omap
    - USE_SOFT_LABEL: true
    - USE_WEIGHTS: true
  - OPTIMIZER: !!omap
    - LR: 0.001
    - WEIGHT_DECAY: 0.0001
    - USE_SAM: true
  - SCHEDULER: !!omap
    - STEP_SIZE: 20
    - GAMMA: 0.9
