!!omap
- OUTPUT_DIR: inference_DepressionAnalysis+GB
- SAVE_CONFIG_NAME: config_inference_DepressionAnalysis+GB.yaml
- CKPTS_DIR: /cvhci/temp/wpingcheng/ckpts_new/
- TYPE: A+Conv-BiLSTM-1D+PHQ-Subscores+Mel
- MANUAL_SEED: 1
- LOG_TITLE: Depression Detection with mix Audio(Mel), Conv-BiLSTM-1D, PHQ-Subscores,
    CrossEntropy with weights, ASAM
- DATA: !!omap
  - TRAIN_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database_V2/train/clipped_data/
  - VALID_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database/train/clipped_data/gender_balance
  - VALIDATION_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database_V2/train/original_data/
  - TEST_ROOT_DIR: /cvhci/temp/wpingcheng/DAIC_WOZ-generated_database_V2/test/clipped_data/
  - USE_MEL_SPECTROGRAM: true
  - VISUAL_WITH_GAZE: false
  - PADDING:
  - RESCALE_SIZE:
  - CROP_SIZE:
  - BATCH_SIZE: 500
  - NUM_WORKERS: 0
- MODEL: !!omap
  - PHQ_THRESHOLD: 10
  - EPOCHS: 1
  - WEIGHTS: !!omap
    - TYPE: other
    - DATE:
    - PATH: model_weights
    - NAME: A+Conv-BiLSTM-1D+PHQ-Subscores+Mel+GB+Soft_2022-03-14_173846_score-0.6096.pt
    - CUSTOM_ABSOLUTE_PATH:
    - INCLUDED:
      - audio_net
      - evaluator
  - AUDIO_NET: !!omap
    - INPUT_DIM: 80
    - CONV_HIDDEN: 256
    - LSTM_HIDDEN: 256
    - OUTPUT_DIM: 256
    - NUM_LAYERS: 4
    - ACTIVATION: relu
    - NORM: bn
    - DROPOUT: 0.5
  - EVALUATOR: !!omap
    - PREDICT_TYPE: phq-subscores
    - INPUT_FEATURE_DIM: 256
    - CLASSES_RESOLUTION: 20
    - N_CLASSES: 4
    - N_SUBSCORES: 8
    - STD: 5
  - CRITERION: !!omap
    - USE_SOFT_LABEL: true
    - USE_WEIGHTS: true
  - OPTIMIZER: !!omap
    - LR: 0.001
    - WEIGHT_DECAY: 0.0001
    - USE_SAM: true
  - SCHEDULER: !!omap
    - STEP_SIZE: 10
    - GAMMA: 0.9
